# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         JE
version:      0.053
version_from: lib/JE.pm
installdirs:  site
requires:
    Carp:                          1.01
    constant:                      1.03
    Date::Parse:                   0
    Encode:                        2.08
    Exporter:                      5.57
    List::Util:                    0
    POSIX:                         0
    re:                            0.02
    Scalar::Util:                  1.14
    strict:                        0
    Test::More:                    0
    Tie::RefHash::Weak:            0
    Time::Local:                   0
    Time::Zone:                    0
    utf8:                          0
    warnings:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
